if __name__ == "__main__":
    print("There is nothing to tell! He's just some guy I work with!")
    print("C'mon, you're going out with the guy...")
    print("Eru Iluvatar himself.")
    print("Aragorn...")
    print("Liv Tyler...")
    print("Gimli...")
    print("Sal Paradise...")
    print("Dean Moriarty...")
    print("Zelda (L)")
    print("Link")
    print("Midna")
    print("Sage")
