name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  workflow-1:
    uses: willianantunes/reusable-workflows/agnostic/evaluate-pr-best-practices.yaml@main
